// Complete inventory, mirrored from the bot (perks.js). Keys must match the game exactly.
export const CATALOG = {
  power: [
    { key: "_EveryPower", name: "★ All Powers" },
    { key: "ACT4", name: "ACT4 (SVJ)" },
    { key: "Shazam", name: "Shazam" },
    { key: "Magic", name: "Magic" },
    { key: "Flash", name: "Flash" },
    { key: "ReverseFlash", name: "Reverse Flash" },
    { key: "Batman", name: "Batman" },
    { key: "SpiderMan", name: "Spider-Man" },
    { key: "Venom", name: "Venom" },
    { key: "Wolverine", name: "Wolverine" },
    { key: "RedHulk", name: "Red Hulk" },
    { key: "Joker", name: "Joker" },
    { key: "GreenGoblin", name: "Green Goblin" },
    { key: "GreenLantern", name: "Green Lantern" },
    { key: "GreenLanternFemale", name: "Green Lantern ♀" },
    { key: "Invincible", name: "Invincible" },
    { key: "Nightwing", name: "Nightwing" },
    { key: "CatWoman", name: "Catwoman" },
    { key: "Blackpanther", name: "Black Panther" },
    { key: "BlackPower", name: "Black Power" },
    { key: "Ghost", name: "Ghost" },
    { key: "Scorpion", name: "Scorpion" },
    { key: "OPKatana", name: "OP Katana" },
    { key: "Fly", name: "Fly" },
    { key: "PurpleFlameOn", name: "Purple Flame" },
    { key: "OrangeFlameOn", name: "Orange Flame" },
    { key: "GreenLanternMale", name: "Green Lantern Male" },
    { key: "escape", name: "Escape" },
    { key: "river", name: "River" },
    { key: "scorpion", name: "Scorpion" },
    { key: "whip", name: "Whip" },
  ],
  stand: [
    { key: "TW", name: "The World" },
    { key: "WonderOfU", name: "Wonder of U" },
    { key: "D4C", name: "D4C" },
    { key: "TA4", name: "ACT4 (SVJ)" },
  ],
  gamepass: [
    { key: "Armor", name: "Spawn with Armor" },
    { key: "AimLock", name: "Aim Lock" },
    { key: "Aimviewer", name: "Aim Viewer" },
    { key: "Mask", name: "Spawn with Mask" },
    { key: "SpawnStim", name: "Spawn with Stim" },
    { key: "SpawnFood", name: "Spawn with Food" },
    { key: "SpawnCookie", name: "Spawn with Cookie" },
    { key: "Katana", name: "Spawn with Katana" },
  ],
  tool: [
    { key: "AdminBat", name: "Admin Bat" },
    { key: "Batarang", name: "Batarang" },
    { key: "BatmanOutfit", name: "Batman Outfit" },
    { key: "Cards", name: "Cards" },
    { key: "Cat Speed", name: "Cat Speed" },
    { key: "CatwomanWhip", name: "Catwoman Whip" },
    { key: "Cuff", name: "Cuff" },
    { key: "D4C", name: "D4C" },
    { key: "Dash Punch", name: "Dash Punch" },
    { key: "Energy Hammer", name: "Energy Hammer" },
    { key: "EnergyBeam", name: "Energy Beam" },
    { key: "Escape", name: "Escape" },
    { key: "FirePower", name: "Fire Power" },
    { key: "FlashTransformation", name: "Flash Transformation" },
    { key: "Flight", name: "Flight" },
    { key: "Fly", name: "Fly" },
    { key: "Ghost", name: "Ghost" },
    { key: "Ghost Ray", name: "Ghost Ray" },
    { key: "Glide", name: "Glide" },
    { key: "GoblinGlider", name: "Goblin Glider" },
    { key: "GoblinGrenade", name: "Goblin Grenade" },
    { key: "GrappleHook", name: "Grapple Hook" },
    { key: "GreenGoblinOutfit", name: "Green Goblin Outfit" },
    { key: "GreenLanternOutfit", name: "Green Lantern Outfit" },
    { key: "Hearing", name: "Hearing" },
    { key: "InvincibleOutfit", name: "Invincible Outfit" },
    { key: "Joker Speed", name: "Joker Speed" },
    { key: "JokerCard", name: "Joker Card" },
    { key: "JokerOutfit", name: "Joker Outfit" },
    { key: "Laser Eyes", name: "Laser Eyes" },
    { key: "Lightning Smite", name: "Lightning Smite" },
    { key: "ReverseFlashOutfit", name: "Reverse Flash Outfit" },
    { key: "SpeedForce", name: "Speed Force" },
    { key: "Spiderman", name: "Spiderman" },
    { key: "SuperPunch", name: "Super Punch" },
    { key: "TA4", name: "TA4" },
    { key: "Thunder Clap", name: "Thunder Clap" },
    { key: "Titan", name: "Titan" },
    { key: "Wonder of U", name: "Wonder of U" },
    { key: "[Aimviewer]", name: "Aimviewer" },
    { key: "[BlueFlower]", name: "Blue Flower" },
    { key: "[Boombox]", name: "Boombox" },
    { key: "[BrownBag]", name: "Brown Bag" },
    { key: "[Camera]", name: "Camera" },
    { key: "[Chicken]", name: "Chicken" },
    { key: "[Cleaning Bucket]", name: "Cleaning Bucket" },
    { key: "[Cookie]", name: "Cookie" },
    { key: "[Cranberry]", name: "Cranberry" },
    { key: "[Da Milk]", name: "Da Milk" },
    { key: "[Donut]", name: "Donut" },
    { key: "[DooM]", name: "Doo M" },
    { key: "[Double-Barrel SG]", name: "Double-Barrel SG" },
    { key: "[Firework]", name: "Firework" },
    { key: "[Flashbang]", name: "Flashbang" },
    { key: "[Flashlight]", name: "Flashlight" },
    { key: "[Grenade]", name: "Grenade" },
    { key: "[Hamburger]", name: "Hamburger" },
    { key: "[HeavyWeights]", name: "Heavy Weights" },
    { key: "[HotDog]", name: "Hot Dog" },
    { key: "[HouseKey]", name: "House Key" },
    { key: "[KatanaOP]", name: "Katana OP" },
    { key: "[Katana]", name: "Katana" },
    { key: "[Key]", name: "Key" },
    { key: "[Knife]", name: "Knife" },
    { key: "[Lemonade]", name: "Lemonade" },
    { key: "[Lettuce]", name: "Lettuce" },
    { key: "[Light Magic]", name: "Light Magic" },
    { key: "[Mask]", name: "Mask" },
    { key: "[Meat]", name: "Meat" },
    { key: "[Minigun]", name: "Minigun" },
    { key: "[Mjolnir]", name: "Mjolnir" },
    { key: "[Money Gun]", name: "Money Gun" },
    { key: "[Nunchucks]", name: "Nunchucks" },
    { key: "[OP Katana]", name: "OP Katana" },
    { key: "[Pencil]", name: "Pencil" },
    { key: "[PepperSpray]", name: "Pepper Spray" },
    { key: "[PinkFlower]", name: "Pink Flower" },
    { key: "[Pitchfork]", name: "Pitchfork" },
    { key: "[Pizza]", name: "Pizza" },
    { key: "[Popcorn]", name: "Popcorn" },
    { key: "[PurpleFlower]", name: "Purple Flower" },
    { key: "[Revolver]", name: "Revolver" },
    { key: "[River]", name: "River" },
    { key: "[Scorpion]", name: "Scorpion" },
    { key: "[Shazam]", name: "Shazam" },
    { key: "[Shovel]", name: "Shovel" },
    { key: "[Starblox Latte]", name: "Starblox Latte" },
    { key: "[Stim]", name: "Stim" },
    { key: "[Taco]", name: "Taco" },
    { key: "[TacticalShotgun]", name: "Tactical Shotgun" },
    { key: "[TearGas]", name: "Tear Gas" },
    { key: "[Wallet]", name: "Wallet" },
    { key: "[Weights]", name: "Weights" },
    { key: "[Whip]", name: "Whip" },
    { key: "[YellowFlower]", name: "Yellow Flower" },
    { key: "[hello kitty]", name: "hello kitty" },
  ],
  perk: [
    { key: "Armor", name: "Armor (max)" },
  ],
};
export function findItem(category, key) { return (CATALOG[category] || []).find((i) => i.key === key); }
