// Verified against the live game.
// power -> DiscordAdminPowerGrantV1 | gamepass -> DiscordAdminGrantV1
// stand/car -> DashboardGrant -> _G.DashboardGrants:HasGrant -> StandsHandler / SVJCarManager on spawn
export const CATALOG = {
  power: [
    { key: "_EveryPower", name: "★ All Powers" },
    { key: "ACT4", name: "ACT4 (SVJ)" }, { key: "Batman", name: "Batman" },
    { key: "SpiderMan", name: "Spider-Man" }, { key: "RedHulk", name: "Red Hulk" },
    { key: "Joker", name: "Joker" }, { key: "GreenGoblin", name: "Green Goblin" },
    { key: "GreenLanternMale", name: "Green Lantern ♂" }, { key: "GreenLanternFemale", name: "Green Lantern ♀" },
    { key: "Invincible", name: "Invincible" }, { key: "Nightwing", name: "Nightwing" },
    { key: "CatWoman", name: "Catwoman" }, { key: "BlackPower", name: "Black Power" },
    { key: "Ghost", name: "Ghost" }, { key: "ReverseFlash", name: "Reverse Flash" },
    { key: "OPKatana", name: "OP Katana" },
  ],
  stand: [
    { key: "SoftAndWet", name: "Soft & Wet" }, { key: "TheWorld", name: "The World" },
    { key: "StarPlatinum", name: "Star Platinum" }, { key: "WonderOfU", name: "Wonder of U" },
    { key: "D4C", name: "D4C" },
  ],
  car: [
    { key: "SVJCar", name: "SVJ Car" },
  ],
  tool: [
    { key: "AdminBat", name: "AdminBat" },
    { key: "Batarang", name: "Batarang" },
    { key: "BatmanOutfit", name: "BatmanOutfit" },
    { key: "Cards", name: "Cards" },
    { key: "Cat Speed", name: "Cat Speed" },
    { key: "CatwomanWhip", name: "CatwomanWhip" },
    { key: "Cuff", name: "Cuff" },
    { key: "Dash Punch", name: "Dash Punch" },
    { key: "Energy Hammer", name: "Energy Hammer" },
    { key: "EnergyBeam", name: "EnergyBeam" },
    { key: "Escape", name: "Escape" },
    { key: "FirePower", name: "FirePower" },
    { key: "FlashTransformation", name: "FlashTransformation" },
    { key: "Flight", name: "Flight" },
    { key: "Fly", name: "Fly" },
    { key: "Ghost", name: "Ghost" },
    { key: "Ghost Ray", name: "Ghost Ray" },
    { key: "Glide", name: "Glide" },
    { key: "GoblinGlider", name: "GoblinGlider" },
    { key: "GoblinGrenade", name: "GoblinGrenade" },
    { key: "GrappleHook", name: "GrappleHook" },
    { key: "GreenGoblinOutfit", name: "GreenGoblinOutfit" },
    { key: "GreenLanternOutfit", name: "GreenLanternOutfit" },
    { key: "Hearing", name: "Hearing" },
    { key: "InvincibleOutfit", name: "InvincibleOutfit" },
    { key: "Joker Speed", name: "Joker Speed" },
    { key: "JokerCard", name: "JokerCard" },
    { key: "JokerOutfit", name: "JokerOutfit" },
    { key: "Laser Eyes", name: "Laser Eyes" },
    { key: "Lightning Smite", name: "Lightning Smite" },
    { key: "ReverseFlashOutfit", name: "ReverseFlashOutfit" },
    { key: "SpeedForce", name: "SpeedForce" },
    { key: "Spiderman", name: "Spiderman" },
    { key: "SuperPunch", name: "SuperPunch" },
    { key: "TA4", name: "TA4" },
    { key: "Thunder Clap", name: "Thunder Clap" },
    { key: "Titan", name: "Titan" },
    { key: "[Aimviewer]", name: "Aimviewer" },
    { key: "[BlueFlower]", name: "BlueFlower" },
    { key: "[Boombox]", name: "Boombox" },
    { key: "[BrownBag]", name: "BrownBag" },
    { key: "[Camera]", name: "Camera" },
    { key: "[Chicken]", name: "Chicken" },
    { key: "[Cleaning Bucket]", name: "Cleaning Bucket" },
    { key: "[Cookie]", name: "Cookie" },
    { key: "[Cranberry]", name: "Cranberry" },
    { key: "[Da Milk]", name: "Da Milk" },
    { key: "[Donut]", name: "Donut" },
    { key: "[DooM]", name: "DooM" },
    { key: "[Double-Barrel SG]", name: "Double-Barrel SG" },
    { key: "[Firework]", name: "Firework" },
    { key: "[Flashbang]", name: "Flashbang" },
    { key: "[Flashlight]", name: "Flashlight" },
    { key: "[Grenade]", name: "Grenade" },
    { key: "[Hamburger]", name: "Hamburger" },
    { key: "[HeavyWeights]", name: "HeavyWeights" },
    { key: "[HotDog]", name: "HotDog" },
    { key: "[HouseKey]", name: "HouseKey" },
    { key: "[KatanaOP]", name: "KatanaOP" },
    { key: "[Katana]", name: "Katana" },
    { key: "[Key]", name: "Key" },
    { key: "[Knife]", name: "Knife" },
    { key: "[Lemonade]", name: "Lemonade" },
    { key: "[Lettuce]", name: "Lettuce" },
    { key: "[Light Magic]", name: "Light Magic" },
    { key: "[Mask]", name: "Mask" },
    { key: "[Meat]", name: "Meat" },
    { key: "[Minigun]", name: "Minigun" },
    { key: "[Mjolnir]", name: "Mjolnir" },
    { key: "[Money Gun]", name: "Money Gun" },
    { key: "[Nunchucks]", name: "Nunchucks" },
    { key: "[OP Katana]", name: "OP Katana" },
    { key: "[Pencil]", name: "Pencil" },
    { key: "[PepperSpray]", name: "PepperSpray" },
    { key: "[PinkFlower]", name: "PinkFlower" },
    { key: "[Pitchfork]", name: "Pitchfork" },
    { key: "[Pizza]", name: "Pizza" },
    { key: "[Popcorn]", name: "Popcorn" },
    { key: "[PurpleFlower]", name: "PurpleFlower" },
    { key: "[Revolver]", name: "Revolver" },
    { key: "[River]", name: "River" },
    { key: "[Scorpion]", name: "Scorpion" },
    { key: "[Shazam]", name: "Shazam" },
    { key: "[Shovel]", name: "Shovel" },
    { key: "[Starblox Latte]", name: "Starblox Latte" },
    { key: "[Stim]", name: "Stim" },
    { key: "[Taco]", name: "Taco" },
    { key: "[TacticalShotgun]", name: "TacticalShotgun" },
    { key: "[TearGas]", name: "TearGas" },
    { key: "[Wallet]", name: "Wallet" },
    { key: "[Weights]", name: "Weights" },
    { key: "[Whip]", name: "Whip" },
    { key: "[YellowFlower]", name: "YellowFlower" },
    { key: "[hello kitty]", name: "hello kitty" },
  ],
  gamepass: [
    { key: "Katana", name: "Katana" }, { key: "Armor", name: "Armor" }, { key: "Mask", name: "Mask" },
    { key: "AimLock", name: "Aim Lock" }, { key: "Aimviewer", name: "Aim Viewer" },
    { key: "SpawnFood", name: "Spawn with Food" }, { key: "SpawnStim", name: "Spawn with Stim" }, { key: "SpawnCookie", name: "Spawn with Cookie" },
  ],
};
export function findItem(category, key) { return (CATALOG[category] || []).find((i) => i.key === key); }
